version: '2'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
  bdd:
    image: mariadb:10.6-focal
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=lol
    volumes:
      - ./bdd:/var/lib/mysql
