version: '3'

services:
  backend:
    build: ./backend
    restart: always
    ports:
      - 8080:8080
    networks:
      - tp1
      - tp1_bis
    cpus: 0.1
    mem_limit: 100m
    mem_reservation: 50m
  bdd:
    image: mariadb:10.6-focal
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=lol
    volumes:
      - ./bdd:/var/lib/mysql
    networks:
      - tp1
      - tp1_bis
  frontend:
    build: ./frontend
    restart: always
    ports:
      - 8081:80
    networks:
      - tp1
  frontend2:
    build: ./frontend2
    restart: always
    ports:
      - 8082:80
    networks:
      - tp1_bis

networks:
  tp1:
    driver: bridge
  tp1_bis:
    driver: bridge
